services:
  bc-vip-account-service:
    image: bc-vip-account-service
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bootcampever
    ports:
      - 8082:8080
    environment:
      - SECURITY_USERNAME=admin
      - SECURITY_PASSWORD=password
      - CONFIG_URI=https://config-server-pj2.mybluemix.net
      - ADMIN_URI=https://admin-server-pj2.mybluemix.net
      - PERSONAL_CLIENT_URI=http://172.25.0.2:8080/
networks:
  bootcampever:
    external: true